paths:
  runs_dir: runs
  cache_dir: cache

capture:
  video_enabled: true
  screenshots_enabled: true
  events_enabled: true

  video:
    chunk_seconds: 300    # split recordings into 5-minute segments
    format: mp4

  screenshots:
    interval_seconds: 15  # throttle captures to every 15 seconds
    max_per_minute: 4

  events:
    fine_interval_seconds: 2
    coarse_interval_seconds: 5
    redact_emails: true
    redact_patterns: email, cc16, jwt

logging:
  level: info
  format: json
