paths:
  runs_dir: runs
  cache_dir: cache

capture:
  duration_minutes: 60
  video_enabled: true
  screenshots_enabled: true
  events_enabled: true
  asr_enabled: true
  ocr_enabled: true

  video:
    chunk_seconds: 300    # split recordings into 5-minute segments
    format: mp4

  screenshots:
    interval_seconds: 15  # throttle captures to every 15 seconds
    max_per_minute: 4

  events:
    fine_interval_seconds: 2
    coarse_interval_seconds: 5
    redact_emails: true
    redact_patterns: email, cc16, jwt

  asr:
    meeting_keywords: Zoom, Meet, Teams, Webex
    window_titles: Weekly Sync - Zoom, Design Review - Meet
    whisper_binary: whisper
    language: en

  ocr:
    languages: eng
    tesseract_binary: tesseract

  privacy:
    allow_apps: mail, docs, notes
    allow_urls: https://docs.example.com, https://notes.example.com
    drop_unknown: false

logging:
  level: info
  format: json
